name: Upload to S3

on:
  push:
    branches: [ main ]
  # Manual trigger
  workflow_dispatch:

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 
        
    - name: Upload files to S3
      run: |
        aws s3 sync ./website/ s3://cp-development-eaa-007/

    - name: Notify completion
      run: |
        echo "✅ S3 upload completed successfully!"
        echo "Files uploaded to: s3://cp-development-eaa-007/"
        echo "Timestamp: $(date)"

    - name: Notify on failure
      if: failure()
      run: |
          echo ":( S3 upload failed!"
          echo "Check the logs above for details"
